// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: servers.proto

package serversv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerDTO struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OwnerId     string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Settings    *ServerSettings        `protobuf:"bytes,5,opt,name=settings,proto3" json:"settings,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted   bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// Иконка загружается отдельно через File Service
	IconUrl       *string `protobuf:"bytes,9,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	HasIcon       *bool   `protobuf:"varint,10,opt,name=has_icon,json=hasIcon,proto3,oneof" json:"has_icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerDTO) Reset() {
	*x = ServerDTO{}
	mi := &file_servers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDTO) ProtoMessage() {}

func (x *ServerDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDTO.ProtoReflect.Descriptor instead.
func (*ServerDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{0}
}

func (x *ServerDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerDTO) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ServerDTO) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ServerDTO) GetSettings() *ServerSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ServerDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServerDTO) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ServerDTO) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *ServerDTO) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *ServerDTO) GetHasIcon() bool {
	if x != nil && x.HasIcon != nil {
		return *x.HasIcon
	}
	return false
}

type ServerSettings struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxMembers            int32                  `protobuf:"varint,1,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`
	AllowMemberInvite     bool                   `protobuf:"varint,2,opt,name=allow_member_invite,json=allowMemberInvite,proto3" json:"allow_member_invite,omitempty"`
	AutoModerationEnabled bool                   `protobuf:"varint,3,opt,name=auto_moderation_enabled,json=autoModerationEnabled,proto3" json:"auto_moderation_enabled,omitempty"`
	MaxMessageLength      int32                  `protobuf:"varint,4,opt,name=max_message_length,json=maxMessageLength,proto3" json:"max_message_length,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ServerSettings) Reset() {
	*x = ServerSettings{}
	mi := &file_servers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSettings) ProtoMessage() {}

func (x *ServerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSettings.ProtoReflect.Descriptor instead.
func (*ServerSettings) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{1}
}

func (x *ServerSettings) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *ServerSettings) GetAllowMemberInvite() bool {
	if x != nil {
		return x.AllowMemberInvite
	}
	return false
}

func (x *ServerSettings) GetAutoModerationEnabled() bool {
	if x != nil {
		return x.AutoModerationEnabled
	}
	return false
}

func (x *ServerSettings) GetMaxMessageLength() int32 {
	if x != nil {
		return x.MaxMessageLength
	}
	return 0
}

type CreateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Settings      *ServerSettings        `protobuf:"bytes,4,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_servers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{2}
}

func (x *CreateServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServerRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateServerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateServerRequest) GetSettings() *ServerSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CreateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
	mi := &file_servers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResponse.ProtoReflect.Descriptor instead.
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{3}
}

func (x *CreateServerResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateServerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // Для проверки прав доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_servers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{4}
}

func (x *GetServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetServerRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type UpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UpdaterId     string                 `protobuf:"bytes,2,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Settings      *ServerSettings        `protobuf:"bytes,5,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_servers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateServerRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

func (x *UpdateServerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateServerRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateServerRequest) GetSettings() *ServerSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	DeleterId     string                 `protobuf:"bytes,2,opt,name=deleter_id,json=deleterId,proto3" json:"deleter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_servers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteServerRequest) GetDeleterId() string {
	if x != nil {
		return x.DeleterId
	}
	return ""
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddedBy       string                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_servers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{7}
}

func (x *AddMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMemberRequest) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RemovedBy     string                 `protobuf:"bytes,3,opt,name=removed_by,json=removedBy,proto3" json:"removed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_servers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveMemberRequest) GetRemovedBy() string {
	if x != nil {
		return x.RemovedBy
	}
	return ""
}

type IsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_servers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{9}
}

func (x *IsMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *IsMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"` // ID ролей участника
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_servers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{10}
}

func (x *IsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *IsMemberResponse) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_servers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembersRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMembersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberDTO           `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_servers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{12}
}

func (x *ListMembersResponse) GetMembers() []*MemberDTO {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type MemberDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RoleIds       []string               `protobuf:"bytes,3,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	IsMuted       bool                   `protobuf:"varint,5,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsBanned      bool                   `protobuf:"varint,6,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	MutedUntil    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=muted_until,json=mutedUntil,proto3,oneof" json:"muted_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberDTO) Reset() {
	*x = MemberDTO{}
	mi := &file_servers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberDTO) ProtoMessage() {}

func (x *MemberDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberDTO.ProtoReflect.Descriptor instead.
func (*MemberDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{13}
}

func (x *MemberDTO) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MemberDTO) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MemberDTO) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *MemberDTO) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *MemberDTO) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *MemberDTO) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

func (x *MemberDTO) GetMutedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.MutedUntil
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CreatorId     string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,4,opt,name=color,proto3,oneof" json:"color,omitempty"` // #RRGGBB
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_servers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateRoleRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type RoleDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Position      int32                  `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleDTO) Reset() {
	*x = RoleDTO{}
	mi := &file_servers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDTO) ProtoMessage() {}

func (x *RoleDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDTO.ProtoReflect.Descriptor instead.
func (*RoleDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{15}
}

func (x *RoleDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleDTO) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RoleDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleDTO) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *RoleDTO) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RoleDTO) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RoleDTO) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UpdaterId     string                 `protobuf:"bytes,3,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Permissions   []string               `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_servers_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpdateRoleRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	DeleterId     string                 `protobuf:"bytes,3,opt,name=deleter_id,json=deleterId,proto3" json:"deleter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_servers_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *DeleteRoleRequest) GetDeleterId() string {
	if x != nil {
		return x.DeleterId
	}
	return ""
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	AssignedBy    string                 `protobuf:"bytes,4,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_servers_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{18}
}

func (x *AssignRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignRoleRequest) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

type RemoveRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RemovedBy     string                 `protobuf:"bytes,4,opt,name=removed_by,json=removedBy,proto3" json:"removed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoleRequest) Reset() {
	*x = RemoveRoleRequest{}
	mi := &file_servers_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleRequest) ProtoMessage() {}

func (x *RemoveRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RemoveRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RemoveRoleRequest) GetRemovedBy() string {
	if x != nil {
		return x.RemovedBy
	}
	return ""
}

type CreateServerChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // ← chat_type нет — все чаты на сервере = ChatTypeServer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerChatRequest) Reset() {
	*x = CreateServerChatRequest{}
	mi := &file_servers_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerChatRequest) ProtoMessage() {}

func (x *CreateServerChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerChatRequest.ProtoReflect.Descriptor instead.
func (*CreateServerChatRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{20}
}

func (x *CreateServerChatRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateServerChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServerChatRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type ServerChatDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerChatDTO) Reset() {
	*x = ServerChatDTO{}
	mi := &file_servers_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerChatDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerChatDTO) ProtoMessage() {}

func (x *ServerChatDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerChatDTO.ProtoReflect.Descriptor instead.
func (*ServerChatDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{21}
}

func (x *ServerChatDTO) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ServerChatDTO) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerChatDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerChatDTO) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ServerChatDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListServerChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServerChatsRequest) Reset() {
	*x = ListServerChatsRequest{}
	mi := &file_servers_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServerChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServerChatsRequest) ProtoMessage() {}

func (x *ListServerChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServerChatsRequest.ProtoReflect.Descriptor instead.
func (*ListServerChatsRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{22}
}

func (x *ListServerChatsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListServerChatsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type ListServerChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ServerChatDTO       `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServerChatsResponse) Reset() {
	*x = ListServerChatsResponse{}
	mi := &file_servers_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServerChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServerChatsResponse) ProtoMessage() {}

func (x *ListServerChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServerChatsResponse.ProtoReflect.Descriptor instead.
func (*ListServerChatsResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{23}
}

func (x *ListServerChatsResponse) GetChats() []*ServerChatDTO {
	if x != nil {
		return x.Chats
	}
	return nil
}

type DeleteServerChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	DeleterId     string                 `protobuf:"bytes,3,opt,name=deleter_id,json=deleterId,proto3" json:"deleter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerChatRequest) Reset() {
	*x = DeleteServerChatRequest{}
	mi := &file_servers_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerChatRequest) ProtoMessage() {}

func (x *DeleteServerChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerChatRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteServerChatRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteServerChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *DeleteServerChatRequest) GetDeleterId() string {
	if x != nil {
		return x.DeleterId
	}
	return ""
}

type GetUploadIconURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UploaderId    string                 `protobuf:"bytes,2,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadIconURLRequest) Reset() {
	*x = GetUploadIconURLRequest{}
	mi := &file_servers_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadIconURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadIconURLRequest) ProtoMessage() {}

func (x *GetUploadIconURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadIconURLRequest.ProtoReflect.Descriptor instead.
func (*GetUploadIconURLRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{25}
}

func (x *GetUploadIconURLRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetUploadIconURLRequest) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *GetUploadIconURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetUploadIconURLRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetUploadIconURLRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type GetUploadIconURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadIconURLResponse) Reset() {
	*x = GetUploadIconURLResponse{}
	mi := &file_servers_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadIconURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadIconURLResponse) ProtoMessage() {}

func (x *GetUploadIconURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadIconURLResponse.ProtoReflect.Descriptor instead.
func (*GetUploadIconURLResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{26}
}

func (x *GetUploadIconURLResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetUploadIconURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadIconURLResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *GetUploadIconURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfirmIconUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ConfirmerId   string                 `protobuf:"bytes,3,opt,name=confirmer_id,json=confirmerId,proto3" json:"confirmer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmIconUploadRequest) Reset() {
	*x = ConfirmIconUploadRequest{}
	mi := &file_servers_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmIconUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmIconUploadRequest) ProtoMessage() {}

func (x *ConfirmIconUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmIconUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmIconUploadRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{27}
}

func (x *ConfirmIconUploadRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ConfirmIconUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ConfirmIconUploadRequest) GetConfirmerId() string {
	if x != nil {
		return x.ConfirmerId
	}
	return ""
}

var File_servers_proto protoreflect.FileDescriptor

const file_servers_proto_rawDesc = "" +
	"\n" +
	"\rservers.proto\x12\aservers\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x03\n" +
	"\tServerDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x123\n" +
	"\bsettings\x18\x05 \x01(\v2\x17.servers.ServerSettingsR\bsettings\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted\x12\x1e\n" +
	"\bicon_url\x18\t \x01(\tH\x01R\aiconUrl\x88\x01\x01\x12\x1e\n" +
	"\bhas_icon\x18\n" +
	" \x01(\bH\x02R\ahasIcon\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_icon_urlB\v\n" +
	"\t_has_icon\"\xc7\x01\n" +
	"\x0eServerSettings\x12\x1f\n" +
	"\vmax_members\x18\x01 \x01(\x05R\n" +
	"maxMembers\x12.\n" +
	"\x13allow_member_invite\x18\x02 \x01(\bR\x11allowMemberInvite\x126\n" +
	"\x17auto_moderation_enabled\x18\x03 \x01(\bR\x15autoModerationEnabled\x12,\n" +
	"\x12max_message_length\x18\x04 \x01(\x05R\x10maxMessageLength\"\xc2\x01\n" +
	"\x13CreateServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x128\n" +
	"\bsettings\x18\x04 \x01(\v2\x17.servers.ServerSettingsH\x01R\bsettings\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_settings\"n\n" +
	"\x14CreateServerResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"R\n" +
	"\x10GetServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\"\xf1\x01\n" +
	"\x13UpdateServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x02 \x01(\tR\tupdaterId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x128\n" +
	"\bsettings\x18\x05 \x01(\v2\x17.servers.ServerSettingsH\x02R\bsettings\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_settings\"Q\n" +
	"\x13DeleteServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"deleter_id\x18\x02 \x01(\tR\tdeleterId\"c\n" +
	"\x10AddMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\tR\aaddedBy\"j\n" +
	"\x13RemoveMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"removed_by\x18\x03 \x01(\tR\tremovedBy\"G\n" +
	"\x0fIsMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"J\n" +
	"\x10IsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\"_\n" +
	"\x12ListMembersRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"^\n" +
	"\x13ListMembersResponse\x12,\n" +
	"\amembers\x18\x01 \x03(\v2\x12.servers.MemberDTOR\amembers\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\x9f\x02\n" +
	"\tMemberDTO\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x19\n" +
	"\brole_ids\x18\x03 \x03(\tR\aroleIds\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12\x19\n" +
	"\bis_muted\x18\x05 \x01(\bR\aisMuted\x12\x1b\n" +
	"\tis_banned\x18\x06 \x01(\bR\bisBanned\x12@\n" +
	"\vmuted_until\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"mutedUntil\x88\x01\x01B\x0e\n" +
	"\f_muted_until\"\xaa\x01\n" +
	"\x11CreateRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x04 \x01(\tH\x00R\x05color\x88\x01\x01\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissionsB\b\n" +
	"\x06_color\"\xbd\x01\n" +
	"\aRoleDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\"\xd1\x01\n" +
	"\x11UpdateRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x03 \x01(\tR\tupdaterId\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x01R\x05color\x88\x01\x01\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissionsB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_color\"h\n" +
	"\x11DeleteRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"deleter_id\x18\x03 \x01(\tR\tdeleterId\"\x83\x01\n" +
	"\x11AssignRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1f\n" +
	"\vassigned_by\x18\x04 \x01(\tR\n" +
	"assignedBy\"\x81\x01\n" +
	"\x11RemoveRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"removed_by\x18\x04 \x01(\tR\tremovedBy\"i\n" +
	"\x17CreateServerChatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\"\xb0\x01\n" +
	"\rServerChatDTO\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"X\n" +
	"\x16ListServerChatsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\"G\n" +
	"\x17ListServerChatsResponse\x12,\n" +
	"\x05chats\x18\x01 \x03(\v2\x16.servers.ServerChatDTOR\x05chats\"n\n" +
	"\x17DeleteServerChatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"deleter_id\x18\x03 \x01(\tR\tdeleterId\"\xae\x01\n" +
	"\x17GetUploadIconURLRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vuploader_id\x18\x02 \x01(\tR\n" +
	"uploaderId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\"\xac\x01\n" +
	"\x18GetUploadIconURLResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"s\n" +
	"\x18ConfirmIconUploadRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12!\n" +
	"\fconfirmer_id\x18\x03 \x01(\tR\vconfirmerId2\x95\n" +
	"\n" +
	"\x0eServersService\x12K\n" +
	"\fCreateServer\x12\x1c.servers.CreateServerRequest\x1a\x1d.servers.CreateServerResponse\x12:\n" +
	"\tGetServer\x12\x19.servers.GetServerRequest\x1a\x12.servers.ServerDTO\x12D\n" +
	"\fUpdateServer\x12\x1c.servers.UpdateServerRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fDeleteServer\x12\x1c.servers.DeleteServerRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tAddMember\x12\x19.servers.AddMemberRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fRemoveMember\x12\x1c.servers.RemoveMemberRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\bIsMember\x12\x18.servers.IsMemberRequest\x1a\x19.servers.IsMemberResponse\x12H\n" +
	"\vListMembers\x12\x1b.servers.ListMembersRequest\x1a\x1c.servers.ListMembersResponse\x12:\n" +
	"\n" +
	"CreateRole\x12\x1a.servers.CreateRoleRequest\x1a\x10.servers.RoleDTO\x12@\n" +
	"\n" +
	"UpdateRole\x12\x1a.servers.UpdateRoleRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteRole\x12\x1a.servers.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"AssignRole\x12\x1a.servers.AssignRoleRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"RemoveRole\x12\x1a.servers.RemoveRoleRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x10CreateServerChat\x12 .servers.CreateServerChatRequest\x1a\x16.servers.ServerChatDTO\x12T\n" +
	"\x0fListServerChats\x12\x1f.servers.ListServerChatsRequest\x1a .servers.ListServerChatsResponse\x12L\n" +
	"\x10DeleteServerChat\x12 .servers.DeleteServerChatRequest\x1a\x16.google.protobuf.Empty\x12W\n" +
	"\x10GetUploadIconURL\x12 .servers.GetUploadIconURLRequest\x1a!.servers.GetUploadIconURLResponse\x12N\n" +
	"\x11ConfirmIconUpload\x12!.servers.ConfirmIconUploadRequest\x1a\x16.google.protobuf.EmptyBHZFgithub.com/MrEsbens/messenger-servers-service/api/servers/v1;serversv1b\x06proto3"

var (
	file_servers_proto_rawDescOnce sync.Once
	file_servers_proto_rawDescData []byte
)

func file_servers_proto_rawDescGZIP() []byte {
	file_servers_proto_rawDescOnce.Do(func() {
		file_servers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servers_proto_rawDesc), len(file_servers_proto_rawDesc)))
	})
	return file_servers_proto_rawDescData
}

var file_servers_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_servers_proto_goTypes = []any{
	(*ServerDTO)(nil),                // 0: servers.ServerDTO
	(*ServerSettings)(nil),           // 1: servers.ServerSettings
	(*CreateServerRequest)(nil),      // 2: servers.CreateServerRequest
	(*CreateServerResponse)(nil),     // 3: servers.CreateServerResponse
	(*GetServerRequest)(nil),         // 4: servers.GetServerRequest
	(*UpdateServerRequest)(nil),      // 5: servers.UpdateServerRequest
	(*DeleteServerRequest)(nil),      // 6: servers.DeleteServerRequest
	(*AddMemberRequest)(nil),         // 7: servers.AddMemberRequest
	(*RemoveMemberRequest)(nil),      // 8: servers.RemoveMemberRequest
	(*IsMemberRequest)(nil),          // 9: servers.IsMemberRequest
	(*IsMemberResponse)(nil),         // 10: servers.IsMemberResponse
	(*ListMembersRequest)(nil),       // 11: servers.ListMembersRequest
	(*ListMembersResponse)(nil),      // 12: servers.ListMembersResponse
	(*MemberDTO)(nil),                // 13: servers.MemberDTO
	(*CreateRoleRequest)(nil),        // 14: servers.CreateRoleRequest
	(*RoleDTO)(nil),                  // 15: servers.RoleDTO
	(*UpdateRoleRequest)(nil),        // 16: servers.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),        // 17: servers.DeleteRoleRequest
	(*AssignRoleRequest)(nil),        // 18: servers.AssignRoleRequest
	(*RemoveRoleRequest)(nil),        // 19: servers.RemoveRoleRequest
	(*CreateServerChatRequest)(nil),  // 20: servers.CreateServerChatRequest
	(*ServerChatDTO)(nil),            // 21: servers.ServerChatDTO
	(*ListServerChatsRequest)(nil),   // 22: servers.ListServerChatsRequest
	(*ListServerChatsResponse)(nil),  // 23: servers.ListServerChatsResponse
	(*DeleteServerChatRequest)(nil),  // 24: servers.DeleteServerChatRequest
	(*GetUploadIconURLRequest)(nil),  // 25: servers.GetUploadIconURLRequest
	(*GetUploadIconURLResponse)(nil), // 26: servers.GetUploadIconURLResponse
	(*ConfirmIconUploadRequest)(nil), // 27: servers.ConfirmIconUploadRequest
	(*timestamppb.Timestamp)(nil),    // 28: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 29: google.protobuf.Empty
}
var file_servers_proto_depIdxs = []int32{
	1,  // 0: servers.ServerDTO.settings:type_name -> servers.ServerSettings
	28, // 1: servers.ServerDTO.created_at:type_name -> google.protobuf.Timestamp
	28, // 2: servers.ServerDTO.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: servers.CreateServerRequest.settings:type_name -> servers.ServerSettings
	28, // 4: servers.CreateServerResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: servers.UpdateServerRequest.settings:type_name -> servers.ServerSettings
	13, // 6: servers.ListMembersResponse.members:type_name -> servers.MemberDTO
	28, // 7: servers.MemberDTO.joined_at:type_name -> google.protobuf.Timestamp
	28, // 8: servers.MemberDTO.muted_until:type_name -> google.protobuf.Timestamp
	28, // 9: servers.ServerChatDTO.created_at:type_name -> google.protobuf.Timestamp
	21, // 10: servers.ListServerChatsResponse.chats:type_name -> servers.ServerChatDTO
	28, // 11: servers.GetUploadIconURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 12: servers.ServersService.CreateServer:input_type -> servers.CreateServerRequest
	4,  // 13: servers.ServersService.GetServer:input_type -> servers.GetServerRequest
	5,  // 14: servers.ServersService.UpdateServer:input_type -> servers.UpdateServerRequest
	6,  // 15: servers.ServersService.DeleteServer:input_type -> servers.DeleteServerRequest
	7,  // 16: servers.ServersService.AddMember:input_type -> servers.AddMemberRequest
	8,  // 17: servers.ServersService.RemoveMember:input_type -> servers.RemoveMemberRequest
	9,  // 18: servers.ServersService.IsMember:input_type -> servers.IsMemberRequest
	11, // 19: servers.ServersService.ListMembers:input_type -> servers.ListMembersRequest
	14, // 20: servers.ServersService.CreateRole:input_type -> servers.CreateRoleRequest
	16, // 21: servers.ServersService.UpdateRole:input_type -> servers.UpdateRoleRequest
	17, // 22: servers.ServersService.DeleteRole:input_type -> servers.DeleteRoleRequest
	18, // 23: servers.ServersService.AssignRole:input_type -> servers.AssignRoleRequest
	19, // 24: servers.ServersService.RemoveRole:input_type -> servers.RemoveRoleRequest
	20, // 25: servers.ServersService.CreateServerChat:input_type -> servers.CreateServerChatRequest
	22, // 26: servers.ServersService.ListServerChats:input_type -> servers.ListServerChatsRequest
	24, // 27: servers.ServersService.DeleteServerChat:input_type -> servers.DeleteServerChatRequest
	25, // 28: servers.ServersService.GetUploadIconURL:input_type -> servers.GetUploadIconURLRequest
	27, // 29: servers.ServersService.ConfirmIconUpload:input_type -> servers.ConfirmIconUploadRequest
	3,  // 30: servers.ServersService.CreateServer:output_type -> servers.CreateServerResponse
	0,  // 31: servers.ServersService.GetServer:output_type -> servers.ServerDTO
	29, // 32: servers.ServersService.UpdateServer:output_type -> google.protobuf.Empty
	29, // 33: servers.ServersService.DeleteServer:output_type -> google.protobuf.Empty
	29, // 34: servers.ServersService.AddMember:output_type -> google.protobuf.Empty
	29, // 35: servers.ServersService.RemoveMember:output_type -> google.protobuf.Empty
	10, // 36: servers.ServersService.IsMember:output_type -> servers.IsMemberResponse
	12, // 37: servers.ServersService.ListMembers:output_type -> servers.ListMembersResponse
	15, // 38: servers.ServersService.CreateRole:output_type -> servers.RoleDTO
	29, // 39: servers.ServersService.UpdateRole:output_type -> google.protobuf.Empty
	29, // 40: servers.ServersService.DeleteRole:output_type -> google.protobuf.Empty
	29, // 41: servers.ServersService.AssignRole:output_type -> google.protobuf.Empty
	29, // 42: servers.ServersService.RemoveRole:output_type -> google.protobuf.Empty
	21, // 43: servers.ServersService.CreateServerChat:output_type -> servers.ServerChatDTO
	23, // 44: servers.ServersService.ListServerChats:output_type -> servers.ListServerChatsResponse
	29, // 45: servers.ServersService.DeleteServerChat:output_type -> google.protobuf.Empty
	26, // 46: servers.ServersService.GetUploadIconURL:output_type -> servers.GetUploadIconURLResponse
	29, // 47: servers.ServersService.ConfirmIconUpload:output_type -> google.protobuf.Empty
	30, // [30:48] is the sub-list for method output_type
	12, // [12:30] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_servers_proto_init() }
func file_servers_proto_init() {
	if File_servers_proto != nil {
		return
	}
	file_servers_proto_msgTypes[0].OneofWrappers = []any{}
	file_servers_proto_msgTypes[2].OneofWrappers = []any{}
	file_servers_proto_msgTypes[5].OneofWrappers = []any{}
	file_servers_proto_msgTypes[13].OneofWrappers = []any{}
	file_servers_proto_msgTypes[14].OneofWrappers = []any{}
	file_servers_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servers_proto_rawDesc), len(file_servers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servers_proto_goTypes,
		DependencyIndexes: file_servers_proto_depIdxs,
		MessageInfos:      file_servers_proto_msgTypes,
	}.Build()
	File_servers_proto = out.File
	file_servers_proto_goTypes = nil
	file_servers_proto_depIdxs = nil
}
