// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: servers.proto

package serversv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerDTO) Reset() {
	*x = ServerDTO{}
	mi := &file_servers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDTO) ProtoMessage() {}

func (x *ServerDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDTO.ProtoReflect.Descriptor instead.
func (*ServerDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{0}
}

func (x *ServerDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerDTO) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ServerDTO) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ServerDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServerDTO) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ServerDTO) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type CreateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_servers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServerRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateServerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
	mi := &file_servers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResponse.ProtoReflect.Descriptor instead.
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{2}
}

func (x *CreateServerResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateServerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_servers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetServerRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type UpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UpdaterId     string                 `protobuf:"bytes,2,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_servers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateServerRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

func (x *UpdateServerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateServerRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	DeleterId     string                 `protobuf:"bytes,2,opt,name=deleter_id,json=deleterId,proto3" json:"deleter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_servers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteServerRequest) GetDeleterId() string {
	if x != nil {
		return x.DeleterId
	}
	return ""
}

type ListUserServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserServersRequest) Reset() {
	*x = ListUserServersRequest{}
	mi := &file_servers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserServersRequest) ProtoMessage() {}

func (x *ListUserServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserServersRequest.ProtoReflect.Descriptor instead.
func (*ListUserServersRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserServersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserServersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserServersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUserServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*ServerDTO           `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserServersResponse) Reset() {
	*x = ListUserServersResponse{}
	mi := &file_servers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserServersResponse) ProtoMessage() {}

func (x *ListUserServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserServersResponse.ProtoReflect.Descriptor instead.
func (*ListUserServersResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserServersResponse) GetServers() []*ServerDTO {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ServerConfigDTO struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ServerId                string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MaxMembers              int32                  `protobuf:"varint,2,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`
	MaxChannels             int32                  `protobuf:"varint,3,opt,name=max_channels,json=maxChannels,proto3" json:"max_channels,omitempty"`
	DefaultNotificationMode string                 `protobuf:"bytes,4,opt,name=default_notification_mode,json=defaultNotificationMode,proto3" json:"default_notification_mode,omitempty"`
	ModerationEnabled       bool                   `protobuf:"varint,5,opt,name=moderation_enabled,json=moderationEnabled,proto3" json:"moderation_enabled,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ServerConfigDTO) Reset() {
	*x = ServerConfigDTO{}
	mi := &file_servers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfigDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfigDTO) ProtoMessage() {}

func (x *ServerConfigDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfigDTO.ProtoReflect.Descriptor instead.
func (*ServerConfigDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{8}
}

func (x *ServerConfigDTO) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerConfigDTO) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *ServerConfigDTO) GetMaxChannels() int32 {
	if x != nil {
		return x.MaxChannels
	}
	return 0
}

func (x *ServerConfigDTO) GetDefaultNotificationMode() string {
	if x != nil {
		return x.DefaultNotificationMode
	}
	return ""
}

func (x *ServerConfigDTO) GetModerationEnabled() bool {
	if x != nil {
		return x.ModerationEnabled
	}
	return false
}

type GetServerConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerConfigRequest) Reset() {
	*x = GetServerConfigRequest{}
	mi := &file_servers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerConfigRequest) ProtoMessage() {}

func (x *GetServerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerConfigRequest.ProtoReflect.Descriptor instead.
func (*GetServerConfigRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{9}
}

func (x *GetServerConfigRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type UpdateServerConfigRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ServerId                string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UpdaterId               string                 `protobuf:"bytes,2,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	MaxMembers              *int32                 `protobuf:"varint,3,opt,name=max_members,json=maxMembers,proto3,oneof" json:"max_members,omitempty"`
	MaxChannels             *int32                 `protobuf:"varint,4,opt,name=max_channels,json=maxChannels,proto3,oneof" json:"max_channels,omitempty"`
	DefaultNotificationMode *string                `protobuf:"bytes,5,opt,name=default_notification_mode,json=defaultNotificationMode,proto3,oneof" json:"default_notification_mode,omitempty"`
	ModerationEnabled       *bool                  `protobuf:"varint,6,opt,name=moderation_enabled,json=moderationEnabled,proto3,oneof" json:"moderation_enabled,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateServerConfigRequest) Reset() {
	*x = UpdateServerConfigRequest{}
	mi := &file_servers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerConfigRequest) ProtoMessage() {}

func (x *UpdateServerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerConfigRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateServerConfigRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateServerConfigRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

func (x *UpdateServerConfigRequest) GetMaxMembers() int32 {
	if x != nil && x.MaxMembers != nil {
		return *x.MaxMembers
	}
	return 0
}

func (x *UpdateServerConfigRequest) GetMaxChannels() int32 {
	if x != nil && x.MaxChannels != nil {
		return *x.MaxChannels
	}
	return 0
}

func (x *UpdateServerConfigRequest) GetDefaultNotificationMode() string {
	if x != nil && x.DefaultNotificationMode != nil {
		return *x.DefaultNotificationMode
	}
	return ""
}

func (x *UpdateServerConfigRequest) GetModerationEnabled() bool {
	if x != nil && x.ModerationEnabled != nil {
		return *x.ModerationEnabled
	}
	return false
}

type ModerationConfigDTO struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ServerId               string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ProfanityFilterAction  string                 `protobuf:"bytes,2,opt,name=profanity_filter_action,json=profanityFilterAction,proto3" json:"profanity_filter_action,omitempty"`
	ToxicityFilterAction   string                 `protobuf:"bytes,3,opt,name=toxicity_filter_action,json=toxicityFilterAction,proto3" json:"toxicity_filter_action,omitempty"`
	NsfwTextFilterAction   string                 `protobuf:"bytes,4,opt,name=nsfw_text_filter_action,json=nsfwTextFilterAction,proto3" json:"nsfw_text_filter_action,omitempty"`
	PoliticalFilterAction  string                 `protobuf:"bytes,5,opt,name=political_filter_action,json=politicalFilterAction,proto3" json:"political_filter_action,omitempty"`
	HateSpeechFilterAction string                 `protobuf:"bytes,6,opt,name=hate_speech_filter_action,json=hateSpeechFilterAction,proto3" json:"hate_speech_filter_action,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ModerationConfigDTO) Reset() {
	*x = ModerationConfigDTO{}
	mi := &file_servers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerationConfigDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerationConfigDTO) ProtoMessage() {}

func (x *ModerationConfigDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerationConfigDTO.ProtoReflect.Descriptor instead.
func (*ModerationConfigDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{11}
}

func (x *ModerationConfigDTO) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ModerationConfigDTO) GetProfanityFilterAction() string {
	if x != nil {
		return x.ProfanityFilterAction
	}
	return ""
}

func (x *ModerationConfigDTO) GetToxicityFilterAction() string {
	if x != nil {
		return x.ToxicityFilterAction
	}
	return ""
}

func (x *ModerationConfigDTO) GetNsfwTextFilterAction() string {
	if x != nil {
		return x.NsfwTextFilterAction
	}
	return ""
}

func (x *ModerationConfigDTO) GetPoliticalFilterAction() string {
	if x != nil {
		return x.PoliticalFilterAction
	}
	return ""
}

func (x *ModerationConfigDTO) GetHateSpeechFilterAction() string {
	if x != nil {
		return x.HateSpeechFilterAction
	}
	return ""
}

type GetModerationConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModerationConfigRequest) Reset() {
	*x = GetModerationConfigRequest{}
	mi := &file_servers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModerationConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModerationConfigRequest) ProtoMessage() {}

func (x *GetModerationConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModerationConfigRequest.ProtoReflect.Descriptor instead.
func (*GetModerationConfigRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{12}
}

func (x *GetModerationConfigRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type UpdateModerationConfigRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ServerId               string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UpdaterId              string                 `protobuf:"bytes,2,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	ProfanityFilterAction  *string                `protobuf:"bytes,3,opt,name=profanity_filter_action,json=profanityFilterAction,proto3,oneof" json:"profanity_filter_action,omitempty"`
	ToxicityFilterAction   *string                `protobuf:"bytes,4,opt,name=toxicity_filter_action,json=toxicityFilterAction,proto3,oneof" json:"toxicity_filter_action,omitempty"`
	NsfwTextFilterAction   *string                `protobuf:"bytes,5,opt,name=nsfw_text_filter_action,json=nsfwTextFilterAction,proto3,oneof" json:"nsfw_text_filter_action,omitempty"`
	PoliticalFilterAction  *string                `protobuf:"bytes,6,opt,name=political_filter_action,json=politicalFilterAction,proto3,oneof" json:"political_filter_action,omitempty"`
	HateSpeechFilterAction *string                `protobuf:"bytes,7,opt,name=hate_speech_filter_action,json=hateSpeechFilterAction,proto3,oneof" json:"hate_speech_filter_action,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateModerationConfigRequest) Reset() {
	*x = UpdateModerationConfigRequest{}
	mi := &file_servers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModerationConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModerationConfigRequest) ProtoMessage() {}

func (x *UpdateModerationConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModerationConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateModerationConfigRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateModerationConfigRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateModerationConfigRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

func (x *UpdateModerationConfigRequest) GetProfanityFilterAction() string {
	if x != nil && x.ProfanityFilterAction != nil {
		return *x.ProfanityFilterAction
	}
	return ""
}

func (x *UpdateModerationConfigRequest) GetToxicityFilterAction() string {
	if x != nil && x.ToxicityFilterAction != nil {
		return *x.ToxicityFilterAction
	}
	return ""
}

func (x *UpdateModerationConfigRequest) GetNsfwTextFilterAction() string {
	if x != nil && x.NsfwTextFilterAction != nil {
		return *x.NsfwTextFilterAction
	}
	return ""
}

func (x *UpdateModerationConfigRequest) GetPoliticalFilterAction() string {
	if x != nil && x.PoliticalFilterAction != nil {
		return *x.PoliticalFilterAction
	}
	return ""
}

func (x *UpdateModerationConfigRequest) GetHateSpeechFilterAction() string {
	if x != nil && x.HateSpeechFilterAction != nil {
		return *x.HateSpeechFilterAction
	}
	return ""
}

type MemberDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RoleIds       []string               `protobuf:"bytes,3,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	IsMuted       bool                   `protobuf:"varint,5,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsBanned      bool                   `protobuf:"varint,6,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	MutedUntil    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=muted_until,json=mutedUntil,proto3,oneof" json:"muted_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberDTO) Reset() {
	*x = MemberDTO{}
	mi := &file_servers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberDTO) ProtoMessage() {}

func (x *MemberDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberDTO.ProtoReflect.Descriptor instead.
func (*MemberDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{14}
}

func (x *MemberDTO) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MemberDTO) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MemberDTO) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *MemberDTO) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *MemberDTO) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *MemberDTO) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

func (x *MemberDTO) GetMutedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.MutedUntil
	}
	return nil
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddedBy       string                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_servers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{15}
}

func (x *AddMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMemberRequest) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RemovedBy     string                 `protobuf:"bytes,3,opt,name=removed_by,json=removedBy,proto3" json:"removed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_servers_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveMemberRequest) GetRemovedBy() string {
	if x != nil {
		return x.RemovedBy
	}
	return ""
}

type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_servers_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{17}
}

func (x *GetMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_servers_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{18}
}

func (x *ListMembersRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMembersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberDTO           `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_servers_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{19}
}

func (x *ListMembersResponse) GetMembers() []*MemberDTO {
	if x != nil {
		return x.Members
	}
	return nil
}

type BanMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BannedBy      string                 `protobuf:"bytes,3,opt,name=banned_by,json=bannedBy,proto3" json:"banned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanMemberRequest) Reset() {
	*x = BanMemberRequest{}
	mi := &file_servers_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanMemberRequest) ProtoMessage() {}

func (x *BanMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanMemberRequest.ProtoReflect.Descriptor instead.
func (*BanMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{20}
}

func (x *BanMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *BanMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanMemberRequest) GetBannedBy() string {
	if x != nil {
		return x.BannedBy
	}
	return ""
}

type UnbanMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UnbannedBy    string                 `protobuf:"bytes,3,opt,name=unbanned_by,json=unbannedBy,proto3" json:"unbanned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanMemberRequest) Reset() {
	*x = UnbanMemberRequest{}
	mi := &file_servers_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanMemberRequest) ProtoMessage() {}

func (x *UnbanMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanMemberRequest.ProtoReflect.Descriptor instead.
func (*UnbanMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{21}
}

func (x *UnbanMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UnbanMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnbanMemberRequest) GetUnbannedBy() string {
	if x != nil {
		return x.UnbannedBy
	}
	return ""
}

type MuteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MutedBy       string                 `protobuf:"bytes,3,opt,name=muted_by,json=mutedBy,proto3" json:"muted_by,omitempty"`
	DurationHours int64                  `protobuf:"varint,4,opt,name=duration_hours,json=durationHours,proto3" json:"duration_hours,omitempty"` // 0 = навсегда
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberRequest) Reset() {
	*x = MuteMemberRequest{}
	mi := &file_servers_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberRequest) ProtoMessage() {}

func (x *MuteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberRequest.ProtoReflect.Descriptor instead.
func (*MuteMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{22}
}

func (x *MuteMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MuteMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MuteMemberRequest) GetMutedBy() string {
	if x != nil {
		return x.MutedBy
	}
	return ""
}

func (x *MuteMemberRequest) GetDurationHours() int64 {
	if x != nil {
		return x.DurationHours
	}
	return 0
}

type UnmuteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UnmutedBy     string                 `protobuf:"bytes,3,opt,name=unmuted_by,json=unmutedBy,proto3" json:"unmuted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmuteMemberRequest) Reset() {
	*x = UnmuteMemberRequest{}
	mi := &file_servers_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmuteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmuteMemberRequest) ProtoMessage() {}

func (x *UnmuteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmuteMemberRequest.ProtoReflect.Descriptor instead.
func (*UnmuteMemberRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{23}
}

func (x *UnmuteMemberRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UnmuteMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnmuteMemberRequest) GetUnmutedBy() string {
	if x != nil {
		return x.UnmutedBy
	}
	return ""
}

type RoleDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Position      int32                  `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleDTO) Reset() {
	*x = RoleDTO{}
	mi := &file_servers_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDTO) ProtoMessage() {}

func (x *RoleDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDTO.ProtoReflect.Descriptor instead.
func (*RoleDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{24}
}

func (x *RoleDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleDTO) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RoleDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleDTO) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *RoleDTO) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RoleDTO) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RoleDTO) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId     string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_servers_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{25}
}

func (x *CreateRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UpdaterId     string                 `protobuf:"bytes,3,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Permissions   []string               `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_servers_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpdateRoleRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	DeleterId     string                 `protobuf:"bytes,3,opt,name=deleter_id,json=deleterId,proto3" json:"deleter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_servers_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *DeleteRoleRequest) GetDeleterId() string {
	if x != nil {
		return x.DeleterId
	}
	return ""
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"` // ← ДОБАВЛЕНО
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	AssignedBy    string                 `protobuf:"bytes,4,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_servers_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{28}
}

func (x *AssignRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AssignRoleRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *AssignRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignRoleRequest) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

type RemoveRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"` // ← ДОБАВЛЕНО
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RemovedBy     string                 `protobuf:"bytes,4,opt,name=removed_by,json=removedBy,proto3" json:"removed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoleRequest) Reset() {
	*x = RemoveRoleRequest{}
	mi := &file_servers_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleRequest) ProtoMessage() {}

func (x *RemoveRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoleRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{29}
}

func (x *RemoveRoleRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RemoveRoleRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *RemoveRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RemoveRoleRequest) GetRemovedBy() string {
	if x != nil {
		return x.RemovedBy
	}
	return ""
}

type GetMemberRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRolesRequest) Reset() {
	*x = GetMemberRolesRequest{}
	mi := &file_servers_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRolesRequest) ProtoMessage() {}

func (x *GetMemberRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRolesRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRolesRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{30}
}

func (x *GetMemberRolesRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type GetMemberRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleDTO             `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRolesResponse) Reset() {
	*x = GetMemberRolesResponse{}
	mi := &file_servers_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRolesResponse) ProtoMessage() {}

func (x *GetMemberRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRolesResponse.ProtoReflect.Descriptor instead.
func (*GetMemberRolesResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{31}
}

func (x *GetMemberRolesResponse) GetRoles() []*RoleDTO {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ServerChatDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerChatDTO) Reset() {
	*x = ServerChatDTO{}
	mi := &file_servers_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerChatDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerChatDTO) ProtoMessage() {}

func (x *ServerChatDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerChatDTO.ProtoReflect.Descriptor instead.
func (*ServerChatDTO) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{32}
}

func (x *ServerChatDTO) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ServerChatDTO) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerChatDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerChatDTO) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ServerChatDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateServerChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerChatRequest) Reset() {
	*x = CreateServerChatRequest{}
	mi := &file_servers_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerChatRequest) ProtoMessage() {}

func (x *CreateServerChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerChatRequest.ProtoReflect.Descriptor instead.
func (*CreateServerChatRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{33}
}

func (x *CreateServerChatRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateServerChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServerChatRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type ListServerChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServerChatsRequest) Reset() {
	*x = ListServerChatsRequest{}
	mi := &file_servers_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServerChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServerChatsRequest) ProtoMessage() {}

func (x *ListServerChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServerChatsRequest.ProtoReflect.Descriptor instead.
func (*ListServerChatsRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{34}
}

func (x *ListServerChatsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListServerChatsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type ListServerChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ServerChatDTO       `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServerChatsResponse) Reset() {
	*x = ListServerChatsResponse{}
	mi := &file_servers_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServerChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServerChatsResponse) ProtoMessage() {}

func (x *ListServerChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServerChatsResponse.ProtoReflect.Descriptor instead.
func (*ListServerChatsResponse) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{35}
}

func (x *ListServerChatsResponse) GetChats() []*ServerChatDTO {
	if x != nil {
		return x.Chats
	}
	return nil
}

type DeleteServerChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	DeleterId     string                 `protobuf:"bytes,3,opt,name=deleter_id,json=deleterId,proto3" json:"deleter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerChatRequest) Reset() {
	*x = DeleteServerChatRequest{}
	mi := &file_servers_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerChatRequest) ProtoMessage() {}

func (x *DeleteServerChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerChatRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteServerChatRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteServerChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *DeleteServerChatRequest) GetDeleterId() string {
	if x != nil {
		return x.DeleterId
	}
	return ""
}

var File_servers_proto protoreflect.FileDescriptor

const file_servers_proto_rawDesc = "" +
	"\n" +
	"\rservers.proto\x12\aservers\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\tServerDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bR\tisDeletedB\x0e\n" +
	"\f_description\"{\n" +
	"\x13CreateServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerIdB\x0e\n" +
	"\f_description\"n\n" +
	"\x14CreateServerResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"R\n" +
	"\x10GetServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\"\xaa\x01\n" +
	"\x13UpdateServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x02 \x01(\tR\tupdaterId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"Q\n" +
	"\x13DeleteServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"deleter_id\x18\x02 \x01(\tR\tdeleterId\"_\n" +
	"\x16ListUserServersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"G\n" +
	"\x17ListUserServersResponse\x12,\n" +
	"\aservers\x18\x01 \x03(\v2\x12.servers.ServerDTOR\aservers\"\xdd\x01\n" +
	"\x0fServerConfigDTO\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vmax_members\x18\x02 \x01(\x05R\n" +
	"maxMembers\x12!\n" +
	"\fmax_channels\x18\x03 \x01(\x05R\vmaxChannels\x12:\n" +
	"\x19default_notification_mode\x18\x04 \x01(\tR\x17defaultNotificationMode\x12-\n" +
	"\x12moderation_enabled\x18\x05 \x01(\bR\x11moderationEnabled\"5\n" +
	"\x16GetServerConfigRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\xf0\x02\n" +
	"\x19UpdateServerConfigRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x02 \x01(\tR\tupdaterId\x12$\n" +
	"\vmax_members\x18\x03 \x01(\x05H\x00R\n" +
	"maxMembers\x88\x01\x01\x12&\n" +
	"\fmax_channels\x18\x04 \x01(\x05H\x01R\vmaxChannels\x88\x01\x01\x12?\n" +
	"\x19default_notification_mode\x18\x05 \x01(\tH\x02R\x17defaultNotificationMode\x88\x01\x01\x122\n" +
	"\x12moderation_enabled\x18\x06 \x01(\bH\x03R\x11moderationEnabled\x88\x01\x01B\x0e\n" +
	"\f_max_membersB\x0f\n" +
	"\r_max_channelsB\x1c\n" +
	"\x1a_default_notification_modeB\x15\n" +
	"\x13_moderation_enabled\"\xca\x02\n" +
	"\x13ModerationConfigDTO\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x126\n" +
	"\x17profanity_filter_action\x18\x02 \x01(\tR\x15profanityFilterAction\x124\n" +
	"\x16toxicity_filter_action\x18\x03 \x01(\tR\x14toxicityFilterAction\x125\n" +
	"\x17nsfw_text_filter_action\x18\x04 \x01(\tR\x14nsfwTextFilterAction\x126\n" +
	"\x17political_filter_action\x18\x05 \x01(\tR\x15politicalFilterAction\x129\n" +
	"\x19hate_speech_filter_action\x18\x06 \x01(\tR\x16hateSpeechFilterAction\"9\n" +
	"\x1aGetModerationConfigRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\x99\x04\n" +
	"\x1dUpdateModerationConfigRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x02 \x01(\tR\tupdaterId\x12;\n" +
	"\x17profanity_filter_action\x18\x03 \x01(\tH\x00R\x15profanityFilterAction\x88\x01\x01\x129\n" +
	"\x16toxicity_filter_action\x18\x04 \x01(\tH\x01R\x14toxicityFilterAction\x88\x01\x01\x12:\n" +
	"\x17nsfw_text_filter_action\x18\x05 \x01(\tH\x02R\x14nsfwTextFilterAction\x88\x01\x01\x12;\n" +
	"\x17political_filter_action\x18\x06 \x01(\tH\x03R\x15politicalFilterAction\x88\x01\x01\x12>\n" +
	"\x19hate_speech_filter_action\x18\a \x01(\tH\x04R\x16hateSpeechFilterAction\x88\x01\x01B\x1a\n" +
	"\x18_profanity_filter_actionB\x19\n" +
	"\x17_toxicity_filter_actionB\x1a\n" +
	"\x18_nsfw_text_filter_actionB\x1a\n" +
	"\x18_political_filter_actionB\x1c\n" +
	"\x1a_hate_speech_filter_action\"\x9f\x02\n" +
	"\tMemberDTO\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x19\n" +
	"\brole_ids\x18\x03 \x03(\tR\aroleIds\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12\x19\n" +
	"\bis_muted\x18\x05 \x01(\bR\aisMuted\x12\x1b\n" +
	"\tis_banned\x18\x06 \x01(\bR\bisBanned\x12@\n" +
	"\vmuted_until\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"mutedUntil\x88\x01\x01B\x0e\n" +
	"\f_muted_until\"c\n" +
	"\x10AddMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\tR\aaddedBy\"j\n" +
	"\x13RemoveMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"removed_by\x18\x03 \x01(\tR\tremovedBy\"H\n" +
	"\x10GetMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"_\n" +
	"\x12ListMembersRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"C\n" +
	"\x13ListMembersResponse\x12,\n" +
	"\amembers\x18\x01 \x03(\v2\x12.servers.MemberDTOR\amembers\"e\n" +
	"\x10BanMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbanned_by\x18\x03 \x01(\tR\bbannedBy\"k\n" +
	"\x12UnbanMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vunbanned_by\x18\x03 \x01(\tR\n" +
	"unbannedBy\"\x8b\x01\n" +
	"\x11MuteMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmuted_by\x18\x03 \x01(\tR\amutedBy\x12%\n" +
	"\x0eduration_hours\x18\x04 \x01(\x03R\rdurationHours\"j\n" +
	"\x13UnmuteMemberRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"unmuted_by\x18\x03 \x01(\tR\tunmutedBy\"\xbd\x01\n" +
	"\aRoleDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\"c\n" +
	"\x11CreateRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\"\xd1\x01\n" +
	"\x11UpdateRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x03 \x01(\tR\tupdaterId\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x01R\x05color\x88\x01\x01\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissionsB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_color\"h\n" +
	"\x11DeleteRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"deleter_id\x18\x03 \x01(\tR\tdeleterId\"\x87\x01\n" +
	"\x11AssignRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1f\n" +
	"\vassigned_by\x18\x04 \x01(\tR\n" +
	"assignedBy\"\x85\x01\n" +
	"\x11RemoveRoleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"removed_by\x18\x04 \x01(\tR\tremovedBy\"4\n" +
	"\x15GetMemberRolesRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"@\n" +
	"\x16GetMemberRolesResponse\x12&\n" +
	"\x05roles\x18\x01 \x03(\v2\x10.servers.RoleDTOR\x05roles\"\xb0\x01\n" +
	"\rServerChatDTO\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"i\n" +
	"\x17CreateServerChatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\"X\n" +
	"\x16ListServerChatsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\"G\n" +
	"\x17ListServerChatsResponse\x12,\n" +
	"\x05chats\x18\x01 \x03(\v2\x16.servers.ServerChatDTOR\x05chats\"n\n" +
	"\x17DeleteServerChatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"deleter_id\x18\x03 \x01(\tR\tdeleterId2\xf0\x0e\n" +
	"\x0eServersService\x12K\n" +
	"\fCreateServer\x12\x1c.servers.CreateServerRequest\x1a\x1d.servers.CreateServerResponse\x12:\n" +
	"\tGetServer\x12\x19.servers.GetServerRequest\x1a\x12.servers.ServerDTO\x12D\n" +
	"\fUpdateServer\x12\x1c.servers.UpdateServerRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fDeleteServer\x12\x1c.servers.DeleteServerRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0fListUserServers\x12\x1f.servers.ListUserServersRequest\x1a .servers.ListUserServersResponse\x12L\n" +
	"\x0fGetServerConfig\x12\x1f.servers.GetServerConfigRequest\x1a\x18.servers.ServerConfigDTO\x12P\n" +
	"\x12UpdateServerConfig\x12\".servers.UpdateServerConfigRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x13GetModerationConfig\x12#.servers.GetModerationConfigRequest\x1a\x1c.servers.ModerationConfigDTO\x12X\n" +
	"\x16UpdateModerationConfig\x12&.servers.UpdateModerationConfigRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tAddMember\x12\x19.servers.AddMemberRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fRemoveMember\x12\x1c.servers.RemoveMemberRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\tGetMember\x12\x19.servers.GetMemberRequest\x1a\x12.servers.MemberDTO\x12H\n" +
	"\vListMembers\x12\x1b.servers.ListMembersRequest\x1a\x1c.servers.ListMembersResponse\x12>\n" +
	"\tBanMember\x12\x19.servers.BanMemberRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vUnbanMember\x12\x1b.servers.UnbanMemberRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"MuteMember\x12\x1a.servers.MuteMemberRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fUnmuteMember\x12\x1c.servers.UnmuteMemberRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\n" +
	"CreateRole\x12\x1a.servers.CreateRoleRequest\x1a\x10.servers.RoleDTO\x12@\n" +
	"\n" +
	"UpdateRole\x12\x1a.servers.UpdateRoleRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteRole\x12\x1a.servers.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"AssignRole\x12\x1a.servers.AssignRoleRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"RemoveRole\x12\x1a.servers.RemoveRoleRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x0eGetMemberRoles\x12\x1e.servers.GetMemberRolesRequest\x1a\x1f.servers.GetMemberRolesResponse\x12L\n" +
	"\x10CreateServerChat\x12 .servers.CreateServerChatRequest\x1a\x16.servers.ServerChatDTO\x12T\n" +
	"\x0fListServerChats\x12\x1f.servers.ListServerChatsRequest\x1a .servers.ListServerChatsResponse\x12L\n" +
	"\x10DeleteServerChat\x12 .servers.DeleteServerChatRequest\x1a\x16.google.protobuf.EmptyBHZFgithub.com/MrEsbens/messenger-servers-service/api/servers/v1;serversv1b\x06proto3"

var (
	file_servers_proto_rawDescOnce sync.Once
	file_servers_proto_rawDescData []byte
)

func file_servers_proto_rawDescGZIP() []byte {
	file_servers_proto_rawDescOnce.Do(func() {
		file_servers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servers_proto_rawDesc), len(file_servers_proto_rawDesc)))
	})
	return file_servers_proto_rawDescData
}

var file_servers_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_servers_proto_goTypes = []any{
	(*ServerDTO)(nil),                     // 0: servers.ServerDTO
	(*CreateServerRequest)(nil),           // 1: servers.CreateServerRequest
	(*CreateServerResponse)(nil),          // 2: servers.CreateServerResponse
	(*GetServerRequest)(nil),              // 3: servers.GetServerRequest
	(*UpdateServerRequest)(nil),           // 4: servers.UpdateServerRequest
	(*DeleteServerRequest)(nil),           // 5: servers.DeleteServerRequest
	(*ListUserServersRequest)(nil),        // 6: servers.ListUserServersRequest
	(*ListUserServersResponse)(nil),       // 7: servers.ListUserServersResponse
	(*ServerConfigDTO)(nil),               // 8: servers.ServerConfigDTO
	(*GetServerConfigRequest)(nil),        // 9: servers.GetServerConfigRequest
	(*UpdateServerConfigRequest)(nil),     // 10: servers.UpdateServerConfigRequest
	(*ModerationConfigDTO)(nil),           // 11: servers.ModerationConfigDTO
	(*GetModerationConfigRequest)(nil),    // 12: servers.GetModerationConfigRequest
	(*UpdateModerationConfigRequest)(nil), // 13: servers.UpdateModerationConfigRequest
	(*MemberDTO)(nil),                     // 14: servers.MemberDTO
	(*AddMemberRequest)(nil),              // 15: servers.AddMemberRequest
	(*RemoveMemberRequest)(nil),           // 16: servers.RemoveMemberRequest
	(*GetMemberRequest)(nil),              // 17: servers.GetMemberRequest
	(*ListMembersRequest)(nil),            // 18: servers.ListMembersRequest
	(*ListMembersResponse)(nil),           // 19: servers.ListMembersResponse
	(*BanMemberRequest)(nil),              // 20: servers.BanMemberRequest
	(*UnbanMemberRequest)(nil),            // 21: servers.UnbanMemberRequest
	(*MuteMemberRequest)(nil),             // 22: servers.MuteMemberRequest
	(*UnmuteMemberRequest)(nil),           // 23: servers.UnmuteMemberRequest
	(*RoleDTO)(nil),                       // 24: servers.RoleDTO
	(*CreateRoleRequest)(nil),             // 25: servers.CreateRoleRequest
	(*UpdateRoleRequest)(nil),             // 26: servers.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),             // 27: servers.DeleteRoleRequest
	(*AssignRoleRequest)(nil),             // 28: servers.AssignRoleRequest
	(*RemoveRoleRequest)(nil),             // 29: servers.RemoveRoleRequest
	(*GetMemberRolesRequest)(nil),         // 30: servers.GetMemberRolesRequest
	(*GetMemberRolesResponse)(nil),        // 31: servers.GetMemberRolesResponse
	(*ServerChatDTO)(nil),                 // 32: servers.ServerChatDTO
	(*CreateServerChatRequest)(nil),       // 33: servers.CreateServerChatRequest
	(*ListServerChatsRequest)(nil),        // 34: servers.ListServerChatsRequest
	(*ListServerChatsResponse)(nil),       // 35: servers.ListServerChatsResponse
	(*DeleteServerChatRequest)(nil),       // 36: servers.DeleteServerChatRequest
	(*timestamppb.Timestamp)(nil),         // 37: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 38: google.protobuf.Empty
}
var file_servers_proto_depIdxs = []int32{
	37, // 0: servers.ServerDTO.created_at:type_name -> google.protobuf.Timestamp
	37, // 1: servers.ServerDTO.updated_at:type_name -> google.protobuf.Timestamp
	37, // 2: servers.CreateServerResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: servers.ListUserServersResponse.servers:type_name -> servers.ServerDTO
	37, // 4: servers.MemberDTO.joined_at:type_name -> google.protobuf.Timestamp
	37, // 5: servers.MemberDTO.muted_until:type_name -> google.protobuf.Timestamp
	14, // 6: servers.ListMembersResponse.members:type_name -> servers.MemberDTO
	24, // 7: servers.GetMemberRolesResponse.roles:type_name -> servers.RoleDTO
	37, // 8: servers.ServerChatDTO.created_at:type_name -> google.protobuf.Timestamp
	32, // 9: servers.ListServerChatsResponse.chats:type_name -> servers.ServerChatDTO
	1,  // 10: servers.ServersService.CreateServer:input_type -> servers.CreateServerRequest
	3,  // 11: servers.ServersService.GetServer:input_type -> servers.GetServerRequest
	4,  // 12: servers.ServersService.UpdateServer:input_type -> servers.UpdateServerRequest
	5,  // 13: servers.ServersService.DeleteServer:input_type -> servers.DeleteServerRequest
	6,  // 14: servers.ServersService.ListUserServers:input_type -> servers.ListUserServersRequest
	9,  // 15: servers.ServersService.GetServerConfig:input_type -> servers.GetServerConfigRequest
	10, // 16: servers.ServersService.UpdateServerConfig:input_type -> servers.UpdateServerConfigRequest
	12, // 17: servers.ServersService.GetModerationConfig:input_type -> servers.GetModerationConfigRequest
	13, // 18: servers.ServersService.UpdateModerationConfig:input_type -> servers.UpdateModerationConfigRequest
	15, // 19: servers.ServersService.AddMember:input_type -> servers.AddMemberRequest
	16, // 20: servers.ServersService.RemoveMember:input_type -> servers.RemoveMemberRequest
	17, // 21: servers.ServersService.GetMember:input_type -> servers.GetMemberRequest
	18, // 22: servers.ServersService.ListMembers:input_type -> servers.ListMembersRequest
	20, // 23: servers.ServersService.BanMember:input_type -> servers.BanMemberRequest
	21, // 24: servers.ServersService.UnbanMember:input_type -> servers.UnbanMemberRequest
	22, // 25: servers.ServersService.MuteMember:input_type -> servers.MuteMemberRequest
	23, // 26: servers.ServersService.UnmuteMember:input_type -> servers.UnmuteMemberRequest
	25, // 27: servers.ServersService.CreateRole:input_type -> servers.CreateRoleRequest
	26, // 28: servers.ServersService.UpdateRole:input_type -> servers.UpdateRoleRequest
	27, // 29: servers.ServersService.DeleteRole:input_type -> servers.DeleteRoleRequest
	28, // 30: servers.ServersService.AssignRole:input_type -> servers.AssignRoleRequest
	29, // 31: servers.ServersService.RemoveRole:input_type -> servers.RemoveRoleRequest
	30, // 32: servers.ServersService.GetMemberRoles:input_type -> servers.GetMemberRolesRequest
	33, // 33: servers.ServersService.CreateServerChat:input_type -> servers.CreateServerChatRequest
	34, // 34: servers.ServersService.ListServerChats:input_type -> servers.ListServerChatsRequest
	36, // 35: servers.ServersService.DeleteServerChat:input_type -> servers.DeleteServerChatRequest
	2,  // 36: servers.ServersService.CreateServer:output_type -> servers.CreateServerResponse
	0,  // 37: servers.ServersService.GetServer:output_type -> servers.ServerDTO
	38, // 38: servers.ServersService.UpdateServer:output_type -> google.protobuf.Empty
	38, // 39: servers.ServersService.DeleteServer:output_type -> google.protobuf.Empty
	7,  // 40: servers.ServersService.ListUserServers:output_type -> servers.ListUserServersResponse
	8,  // 41: servers.ServersService.GetServerConfig:output_type -> servers.ServerConfigDTO
	38, // 42: servers.ServersService.UpdateServerConfig:output_type -> google.protobuf.Empty
	11, // 43: servers.ServersService.GetModerationConfig:output_type -> servers.ModerationConfigDTO
	38, // 44: servers.ServersService.UpdateModerationConfig:output_type -> google.protobuf.Empty
	38, // 45: servers.ServersService.AddMember:output_type -> google.protobuf.Empty
	38, // 46: servers.ServersService.RemoveMember:output_type -> google.protobuf.Empty
	14, // 47: servers.ServersService.GetMember:output_type -> servers.MemberDTO
	19, // 48: servers.ServersService.ListMembers:output_type -> servers.ListMembersResponse
	38, // 49: servers.ServersService.BanMember:output_type -> google.protobuf.Empty
	38, // 50: servers.ServersService.UnbanMember:output_type -> google.protobuf.Empty
	38, // 51: servers.ServersService.MuteMember:output_type -> google.protobuf.Empty
	38, // 52: servers.ServersService.UnmuteMember:output_type -> google.protobuf.Empty
	24, // 53: servers.ServersService.CreateRole:output_type -> servers.RoleDTO
	38, // 54: servers.ServersService.UpdateRole:output_type -> google.protobuf.Empty
	38, // 55: servers.ServersService.DeleteRole:output_type -> google.protobuf.Empty
	38, // 56: servers.ServersService.AssignRole:output_type -> google.protobuf.Empty
	38, // 57: servers.ServersService.RemoveRole:output_type -> google.protobuf.Empty
	31, // 58: servers.ServersService.GetMemberRoles:output_type -> servers.GetMemberRolesResponse
	32, // 59: servers.ServersService.CreateServerChat:output_type -> servers.ServerChatDTO
	35, // 60: servers.ServersService.ListServerChats:output_type -> servers.ListServerChatsResponse
	38, // 61: servers.ServersService.DeleteServerChat:output_type -> google.protobuf.Empty
	36, // [36:62] is the sub-list for method output_type
	10, // [10:36] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_servers_proto_init() }
func file_servers_proto_init() {
	if File_servers_proto != nil {
		return
	}
	file_servers_proto_msgTypes[0].OneofWrappers = []any{}
	file_servers_proto_msgTypes[1].OneofWrappers = []any{}
	file_servers_proto_msgTypes[4].OneofWrappers = []any{}
	file_servers_proto_msgTypes[10].OneofWrappers = []any{}
	file_servers_proto_msgTypes[13].OneofWrappers = []any{}
	file_servers_proto_msgTypes[14].OneofWrappers = []any{}
	file_servers_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servers_proto_rawDesc), len(file_servers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servers_proto_goTypes,
		DependencyIndexes: file_servers_proto_depIdxs,
		MessageInfos:      file_servers_proto_msgTypes,
	}.Build()
	File_servers_proto = out.File
	file_servers_proto_goTypes = nil
	file_servers_proto_depIdxs = nil
}
